Add translation part 04, from start to svelte/motion included
iOiurson/svelte-fr-docs pull request #2
Opened 2023-01-24 08:21 UTC by Ennoriel

2023-01-24 21:59 UTC, iOiurson requested changes

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +La fonction `onMount` permet d'executer un callback dès que le composant a été monté dans le DOM. Elle doit être appelée pendant l'initialisation du composant (mais elle n'a pas besoin de se trouver
```suggestion
La fonction `onMount` permet de planifier l'exécution d'un callback dès que le composant a été monté dans le DOM. Elle doit être appelée pendant l'instantiation du composant (mais elle n'a pas besoin d'être définie *à l'intérieur* du composant ; elle peut être appelée depuis un module externe).
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +`onMount` ne fonctionne pas à l'intérieur d'un [composant côté serveur] (/docs#run-time-server-side-component-api).
```suggestion
`onMount` n'est pas exécutée pas à l'intérieur d'un [composant côté serveur] (/docs#run-time-server-side-component-api).
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Si une fonction est renvoyée par `onMount`, elle sera appelée lorsque le composant sera démonté.
```suggestion
Si une fonction est renvoyée par `onMount`, celle-ci sera appelée lorsque le composant sera démonté.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +	Importez { onMount } from 'svelte';
```suggestion
	import { onMount } from 'svelte';
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +> Ce comportement ne fonctionne que si la fonction passée à `onMount` renvoie une valeur de manière *synchrone*. Les fonctions `async` renvoient toujours un `Promise`, et en tant que telles ne peuven
```suggestion
> Ce comportement ne fonctionne que si la fonction passée à `onMount` renvoie une valeur de manière *synchrone*. Les fonctions `async` renvoient toujours une `Promise`, ce qui implique qu'elles ne peuvent jamais renvoyer une fonction de manière *synchrone*.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Planifie l'exécution d'un callback immédiatement avant la mise à jour du composant après tout changement d'état.
```suggestion
Planifie l'exécution d'un callback immédiatement avant la mise à jour du composant, lorsqu'un changement d'état s'est produit.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +> La première execution du callback s'exécutera just avant l'appel à `onMount` initial.
```suggestion
> La première exécution du callback se produit juste avant l'appel du `onMount` initial.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +> La première execution du callback s'exécutera just après l'appel à `onMount` initial.
```suggestion
> La première exécution du callback se produit juste après l'appel du `onMount` initial.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Parmi `onMount`, `beforeUpdate`, `afterUpdate` et `onDestroy`, c'est le seul qui s'exécute dans un composant côté serveur.
```suggestion
Parmi les callbacks de `onMount`, `beforeUpdate`, `afterUpdate` et `onDestroy`, c'est le seul qui s'exécute dans un composant côté serveur.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +		console.log('le composant est détruit');
```suggestion
		console.log('le composant va être détruit');
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Associe un objet `context` arbitraire avec le composant courant et la `key` spécifiée et retourne cet objet. Le contexte est alors disponible pour les enfants du composant (y compris le contenu en sl
```suggestion
Associe un objet `context` arbitraire au composant courant et à la `key` spécifiée, puis retourne cet objet. Le contexte est alors accessible pour les enfants du composant (y compris le contenu de slot) avec `getContext`.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Comme les fonctions de cycle de vie, elle doit être appelée pendant l'initialisation du composant.
```suggestion
Comme les fonctions de cycle de vie, elle doit être appelée pendant l'instantiation du composant.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +> Le contexte n'est pas intrinsèquement réactif. Si vous avez besoin de valeurs réactives dans le contexte, alors vous pouvez passer un store dans le contexte, qui *va* être réactifs.
```suggestion
> Le contexte n'est pas intrinsèquement réactif. Si vous avez besoin de valeurs réactives dans le contexte, alors vous pouvez passer un store dans le contexte, store qui *sera* réactif.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Récupère le contexte qui appartient au composant parent le plus proche avec la `clé` spécifiée. Doit être appelé pendant l'initialisation du composant.
```suggestion
Récupère le contexte qui appartient au composant parent le plus proche avec la `key` spécifiée. Doit être appelé pendant l'instantiation du composant.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Vérifie si une `clé` donnée a été définie dans le contexte d'un composant parent. Doit être appelé pendant l'initialisation du composant.
```suggestion
Vérifie si une `clé` donnée a été définie dans le contexte d'un composant parent. Doit être appelé pendant l'instantiation du composant.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +contextes: Map<any, any> = getAllContexts()
```suggestion
contexts: Map<any, any> = getAllContexts()
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Récupère l'ensemble de la carte des contextes appartenant au composant parent le plus proche. Doit être appelé pendant l'initialisation du composant. Utile, par exemple, si vous créez un composant de
```suggestion
Récupère l'ensemble des contextes appartenant au composant parent le plus proche. Doit être appelé pendant l'instantiation du composant. Utile, par exemple, si vous créez un composant de manière programmatique et que vous voulez lui passer le contexte existant.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +	const contextes = getAllContexts();
```suggestion
	const contexts = getAllContexts();
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Crée un répartiteur d'événements qui peut être utilisé pour répartir les [événements de composants] (/docs#template-syntaxe-component-directives-on-eventname). Les répartiteurs d'événements sont des
```suggestion
Crée un *dispatcher* d'événements qui peut être utilisé pour distribuer les [événements de composants] (/docs#template-syntaxe-component-directives-on-eventname). Les *dispatchers* d'événements sont des fonctions qui peuvent prendre deux arguments : `name` et `detail`.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Les événements de composants créés avec `createEventDispatcher` créent un [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent). Ces événements ne remontent pas la [chaine des é
```suggestion
Les événements de composants créés avec `createEventDispatcher` créent un [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent). Ces événements ne suivent pas la [chaîne de *bubbling*](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#Event_bubbling_and_capture). L'argument `detail` correspond à la propriété [CustomEvent.detail](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/detail) et peut contenir tout type de données.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +<button on:click="{() => dispatch('notify', 'detail value')}">Fire Event</button>
```suggestion
<button on:click="{() => dispatch('notify', 'detail value')}">Générer un événement</button>
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +		console.log(`Notify fired ! Detail: ${event.detail}`)
```suggestion
		console.log(`Événement reçu ! Détail: ${event.detail}`)
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Les événements peuvent être annulés en passant un troisième paramètre à la fonction dispatch. La fonction renvoie `false` si l'événement est annulé avec `event.preventDefault()`, sinon elle renvoie `
```suggestion
Les événements peuvent être annulables en passant un troisième paramètre à la fonction `dispatch`. La fonction renvoie `false` si l'événement est annulé avec `event.preventDefault()`, sinon elle renvoie `true`.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +			// un auditeur a appelé preventDefault
```suggestion
			// un listener a appelé preventDefault
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Le module `svelte/store` exporte des fonctions pour créer des magasins [readable](/docs#run-time-svelte-store-readable), [writable](/docs#run-time-svelte-store-writable) et [derived](/docs#run-time-s
```suggestion
Le module `svelte/store` exporte des fonctions pour créer des stores [de lecture (*readable*)](/docs#run-time-svelte-store-readable), [d'écriture (*writable*)](/docs#run-time-svelte-store-writable) et [dérivés (*derived*)](/docs#run-time-svelte-store-derived).
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Gardez à l'esprit que vous n'êtes pas *obligé* d'utiliser ces fonctions pour profiter de la [syntaxe réactive `$store`](/docs#component-format-script-4-prefix-stores-with-$-to-access-their-values) da
```suggestion
Gardez à l'esprit que vous n'êtes pas *obligé•e* d'utiliser ces fonctions pour profiter de la [syntaxe réactive `$store`](/docs#component-format-script-4-prefix-stores-with-$-to-access-their-values) dans vos composants. Tout objet qui implémente correctement `.subscribe`, `unsubscribe`, et (éventuellement) `.set` est un store valide, et fonctionnera à la fois avec la syntaxe spéciale, et avec les [stores dérivés](/docs#run-time-svelte-store-derived) de Svelte.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Cela permet d'envelopper presque toute autre bibliothèque de gestion d'état réactif pour l'utiliser dans Svelte. Pour en savoir plus sur le [contrat de magasin](/docs#component-format-script-4-prefix
```suggestion
Cela permet d'envelopper presque toute autre bibliothèque de gestion d'état réactif pour l'utiliser dans Svelte. Renseignez-vous sur le [contrat de store](/docs#component-format-script-4-prefix-stores-with-$-to-access-their-values-store-contract) pour voir à quoi ressemble une implémentation fonctionnelle.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Fonction qui crée un magasin dont les valeurs peuvent être définies à partir de composants "extérieurs". Il est créé comme un objet avec des méthodes supplémentaires `set` et `update`.
```suggestion
Fonction qui crée un store dont les valeurs peuvent être définies à partir de composants "extérieurs". Il est créé comme un objet avec les méthodes supplémentaires `set` et `update`.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +`set` est une méthode qui prend un argument qui est la valeur à définir. La valeur du magasin est remplacée par la valeur de l'argument si elle n'est pas déjà égale à la valeur du magasin.
```suggestion
`set` est une méthode qui prend un argument la valeur à définir. La valeur courante du store est remplacée par la valeur de l'argument si celle-ci n'est pas déjà égale à la valeur courante.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +`update` est une méthode qui prend un argument qui est un callback. Le callback prend la valeur existante du magasin comme argument et renvoie la nouvelle valeur à définir pour le magasin.
```suggestion
`update` est une méthode qui prend un callback comme seul argument. Le callback prend la valeur existante du store comme argument et renvoie la nouvelle valeur à définir pour le store.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +count.set(1); // enregistre '1'.
```suggestion
count.set(1); // affiche '1'.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +}); // enregistre '0'.
```suggestion
}); // affiche '0'.
```

2023-01-24 21:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +count.update(n => n + 1); // journal '2'.
```suggestion
count.update(n => n + 1); // affiche '2'.
```

2023-01-24 22:14 UTC, iOiurson requested changes

2023-01-24 22:14 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Si une fonction est passée comme deuxième argument, elle sera appelée lorsque le nombre d'abonnés passera de zéro à un (mais pas de un à deux, etc.). Cette fonction se verra passer une fonction `set`
```suggestion
Si une fonction est passée comme deuxième argument, elle sera appelée lorsque le nombre d'abonnés au store passera de zéro à un (mais pas de un à deux, etc...). Cette fonction a comme argument une fonction `set` qui peut changer la valeur du magasin. Elle doit retourner une fonction `stop` qui sera appelée lorsque le nombre d'abonnés passera de un à zéro.
```

2023-01-24 22:14 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Importez { writable } de 'svelte/store';
```suggestion
import { writable } from 'svelte/store';
```

2023-01-24 22:14 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +	importez { hasContext } from 'svelte';
```suggestion
	import { hasContext } from 'svelte';
```

2023-01-24 22:14 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +	console.log('got a subscriber');
```suggestion
	console.log('vous avez un abonné');
```

2023-01-24 22:14 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +	return () => console.log('no more subscribers');
```suggestion
	return () => console.log("vous n'avez plus d'abonnés");
```

2023-01-24 22:14 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +}); // enregistre 'got a subscriber', puis '1'.
```suggestion
}); // affiche 'vous avez un abonné', puis '1'.
```

2023-01-24 22:14 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +unsubscribe(); // enregistre "plus d'abonnés".
```suggestion
unsubscribe(); // affiche "vous n'avez plus d'abonnés".
```

2023-01-24 22:14 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +store = readable(valeur?: any, start?: (set: (valeur: any) => void) => () => void)
```suggestion
store = readable(value?: any, start?: (set: (value: any) => void) => () => void)
```

2023-01-24 22:14 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +store = writable(valeur?: any, start?: (set: (valeur: any) => void) => () => void)
```suggestion
store = writable(value?: any, start?: (set: (value: any) => void) => () => void)
```

2023-01-24 22:14 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Crée un magasin dont la valeur ne peut pas être définie de l'extérieur, le premier argument est la valeur initiale du magasin, et le second argument de `readable` est le même que le second argument d
```suggestion
Crée un store dont la valeur ne peut pas être modifiée de l'extérieur. Le premier argument est la valeur initiale du store, le second argument est le même que le second argument de `writable`.
```

2023-01-24 22:14 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Importez { readable } de 'svelte/store';
```suggestion
import { readable } from 'svelte/store';
```

2023-01-24 22:14 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Dérive un magasin à partir d'un ou plusieurs autres magasins. La callback s'exécute initialement lorsque le premier abonné s'abonne, puis à chaque fois que les dépendances du magasin changent.
```suggestion
Dérive un store à partir d'un ou plusieurs autres stores. La callback s'exécute initialement lorsque le premier abonné s'abonne, puis à chaque fois que les dépendances du magasin changent.
```

2023-01-24 22:14 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Dans la version la plus simple, `derived` prend un seul magasin, et le callback renvoie une valeur dérivée.
```suggestion
Dans la version la plus simple, `derived` prend un seul store, et le callback renvoie une valeur dérivée.
```

2023-01-24 22:14 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Importez { derived } de 'svelte/store';
```suggestion
import { derived } from 'svelte/store';
```

2023-01-24 22:14 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +La callback peut définir une valeur de manière asynchrone en acceptant un second argument, `set`, et en l'appelant au moment opportun.
```suggestion
Le callback peut définir une valeur de manière asynchrone en acceptant un second argument, `set`, et en l'appelant au moment opportun.
```

2023-01-24 22:14 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Dans ce cas, vous pouvez également passer un troisième argument à `derived` - la valeur initiale du magasin dérivé avant le premier appel de `set`.
```suggestion
Dans ce cas, vous pouvez également passer un troisième argument à `derived` - la valeur initiale du store dérivé avant le premier appel de `set`.
```

2023-01-24 22:14 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Importez { derived } de 'svelte/store';
```suggestion
import { derived } from 'svelte/store';
```

2023-01-24 22:14 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +valeur: any = get(store)
```suggestion
value: any = get(store)
```

2023-01-24 22:14 UTC, bleucitron commented on svelte/fr/docs/04-run-time.md
> +De manière général, vous devez lire la valeur d'un magasin en vous y abonnant et en utilisant la valeur lorsqu'elle change au fil du temps. Occasionnellement, vous pouvez avoir besoin de récupérer la
```suggestion
De manière générale, il est recommandé de lire la valeur d'un store en vous y abonnant et en utilisant la valeur à mesure qu'elle change. Occasionnellement, vous pouvez avoir besoin de récupérer la valeur d'un store auquel vous n'êtes pas abonné. `get` vous permet de le faire.
```

2023-01-24 22:14 UTC, bleucitron commented on svelte/fr/docs/04-run-time.md
> +> Cela fonctionne en créant un abonnement, en lisant la valeur, puis en se désabonnant. Elle n'est donc pas recommandée dans les chemins de code chauds (!!!).
```suggestion
> Cela fonctionne en créant un abonnement, en lisant la valeur, puis en se désabonnant. Cette méthode n'est donc pas recommandée lorsque le code concerné est exécuté à haute fréquence.
```

2023-01-24 22:14 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Importez { get } de 'svelte/store';
```suggestion
import { get } from 'svelte/store';
```

2023-01-24 22:33 UTC, iOiurson requested changes

2023-01-24 22:33 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Le module `svelte/motion` exporte deux fonctions, `tweened` et `spring`, pour créer des magasins de type `writable` dont les valeurs changent dans le temps après `set` et `update`, plutôt qu'immédiat
```suggestion
Le module `svelte/motion` exporte deux fonctions, `tweened` et `spring`, pour créer des stores de type `writable` dont les valeurs changent dans le temps après `set` et `update`, plutôt qu'immédiatement.
```

2023-01-24 22:33 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Les magasins `tweened` mettent à jour leurs valeurs sur une durée fixe. Les options suivantes sont disponibles:
```suggestion
Les stores `tweened` mettent à jour leur valeur sur une durée fixe. Les options suivantes sont disponibles:
```

2023-01-24 22:33 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +* `duration` (`number` | `function`, default 400) - durée en millisecondes de la transition.
```suggestion
* `duration` (`number` | `function`, par défaut 400) - durée de la transition en millisecondes
```

2023-01-24 22:33 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +* `easing` (`function`, par défaut `t => t`) - une [fonction d'assouplissement](/docs#run-time-svelte-easing)
```suggestion
* `easing` (`function`, par défaut `t => t`) - une [fonction d'assouplissement](/docs#run-time-svelte-easing)
```
```suggestion
* `easing` (`function`, par défaut `t => t`) - une [fonction de lissage](/docs#run-time-svelte-easing)
```

2023-01-24 22:33 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Les deux fonctions retournent une Promise qui se résout lorsque la transition se termine. Si la transition est interrompu, la promesse ne sera jamais résolue.
```suggestion
Les deux fonctions retournent une Promesse qui se résout lorsque la transition se termine. Si la transition est interrompue, la promesse ne sera jamais résolue.
```

2023-01-24 22:33 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +D'emblée, Svelte interpolera entre deux nombres, deux tableaux ou deux objets (tant que les tableaux et les objets ont la même "forme" et que leurs propriétés "leaf" sont également des nombres). (!!!
```suggestion
Gratuitement, Svelte interpolera entre deux nombres, deux tableaux ou deux objets (tant que les tableaux et les objets ont la même "forme" et que leurs propriétés "feuilles" sont également des nombres).
```

2023-01-24 22:33 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +		// this is equivalent to size.update(n => n + 1)
```suggestion
		// équivalent à size.update(n => n + 1)
```

2023-01-24 22:33 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +>embiggen</button>
```suggestion
>grossir</button>
```

2023-01-24 22:33 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Si la valeur initiale est `undefined` ou `null`, le premier changement de valeur prendra effet immédiatement. Ceci est utile lorsque vous avez des valeurs d'interpolation qui sont basées sur des prop
```suggestion
Si la valeur initiale est `undefined` ou `null`, le premier changement de valeur prendra effet immédiatement. Ceci est utile lorsque vous avez des valeurs d'interpolation qui sont basées sur des propriétés de composant et que vous ne voulez pas qu'il y ait de mouvement lors du premier rendu du composant.
```

2023-01-24 22:33 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +L'option `interpolate` vous permet de faire une transition entre *n'importe quelle* valeur arbitraire. Ce doit être une fonction `(a, b) => t => valeur`, où `a` est la valeur de départ, `b` est la va
```suggestion
L'option `interpolate` vous permet de faire une transition entre *n'importe quelles* valeurs arbitraires. Cette option doit être une fonction `(a, b) => t => value`, où `a` est la valeur de départ, `b` est la valeur cible, `t` est un nombre entre 0 et 1, et `value` est le résultat. Par exemple, il est possible d'utiliser [d3-interpolate](https://github.com/d3/d3-interpolate) pour interpoler entre deux couleurs.
```

2023-01-24 22:33 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Un magasin `spring` change progressivement vers sa valeur cible en fonction de ses paramètres `stiffness` et `damping`. Alors que les magasins `tweened` changent leurs valeurs sur une durée fixe, les
```suggestion
Un store `spring` change progressivement vers sa valeur cible en fonction de ses paramètres `stiffness` (raideur) et `damping` (amortissement). Alors que les stores `tweened` changent leur valeur sur une durée fixe, les stores `spring` changent leur valeur sur une durée qui est déterminée par leur vélocité courante, permettant un mouvement plus naturel dans de nombreuses situations. Les options suivantes sont disponibles :
```

2023-01-24 22:33 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +* `stiffness` (`number`, default `0.15`) - une valeur entre 0 et 1 où une valeur plus grande signifie un ressort plus 'serré'.
```suggestion
* `stiffness` (`number`, par défaut `0.15`) - une valeur entre 0 et 1, où une valeur plus grande signifie un ressort plus 'raide'.
```

2023-01-24 22:33 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +* `damping` (`number`, default `0.8`) - une valeur entre 0 et 1 où une valeur plus basse signifie un ressort plus 'élastique'.
```suggestion
* `damping` (`number`, par défaut `0.8`) - une valeur entre 0 et 1, où une valeur plus basse signifie un ressort plus 'élastique'.
```

2023-01-24 22:33 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +* `precision` (`number`, default `0.01`) - détermine le seuil à partir duquel le ressort est considéré comme 'arrêté'. Une valeur plus basse signifie un ressort plus précis.
```suggestion
* `precision` (`number`, par défaut `0.01`) - détermine le seuil à partir duquel le ressort est considéré comme 'arrêté'. Une valeur plus basse signifie un ressort plus précis.
```

2023-01-24 22:33 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Comme avec les magasins [`tweened`](/docs#run-time-svelte-motion-tweened), `set` et `update` retournent une Promise qui se résout si le ressort s'arrêter.
```suggestion
Comme avec les stores [`tweened`](/docs#run-time-svelte-motion-tweened), `set` et `update` retournent une Promesse qui se résout lorsque le ressort s'arrête.
```

2023-01-24 22:33 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Les deux méthodes `set` et `update` peuvent prendre un second argument - un objet avec les propriétés `hard` ou `soft`. `{ hard: true }` fixe immédiatement la valeur cible ; `{ soft: n }` préserve l'
```suggestion
Les deux méthodes `set` et `update` peuvent prendre un second argument - un objet avec les propriétés `hard` ou `soft`. `{ hard: true }` fixe immédiatement la valeur cible ; `{ soft: n }` préserve l'élan actuel pendant `n` secondes avant de s'arrêter. `{ soft: true }` est équivalent à `{ soft: 0.5 }`.
```

2023-01-24 22:33 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +// updates the value immediately
```suggestion
// change la valeur immédiatement
```

2023-01-24 22:33 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +// preserves existing momentum for 1s
```suggestion
// garde l'élan actuel pendant 1s
```

2023-01-24 22:33 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +[Voir un exemple complet sur le tutoriel des magasins de type `spring`.](/tutorial/spring)
```suggestion
[Un exemple complet de store de type `spring` est disponible dans le tutoriel.](/tutorial/spring)
```

2023-01-25 05:42 UTC, Ennoriel commented on svelte/fr/docs/04-run-time.md
> +count.set(1); // enregistre '1'.
Je l'ai accepté mais je suis moyen chaud pour celle là en vrai

2023-01-25 05:43 UTC, Ennoriel commented on svelte/fr/docs/04-run-time.md
> +Si une fonction est passée comme deuxième argument, elle sera appelée lorsque le nombre d'abonnés passera de zéro à un (mais pas de un à deux, etc.). Cette fonction se verra passer une fonction `set`
on écrit soit des points de suspensions, soit "etc.", pas les deux ;)

2023-01-25 07:59 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +count.set(1); // enregistre '1'.
Le 'affiche' est relatif au `console.log` déclenché par le `.subscribe`, pas au `.set`.

2023-01-25 08:06 UTC, iOiurson requested changes

2023-01-25 08:06 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Gratuitement, Svelte interpolera entre deux nombres, deux tableaux ou deux objets (tant que les tableaux et les objets ont la même "forme" et que leurs propriétés "feuilles" sont également des nombre
```suggestion
Sans que vous n'ayez rien à faire, Svelte interpolera entre deux nombres, deux tableaux ou deux objets (tant que les tableaux et les objets ont la même "forme" et que leurs propriétés "feuilles" sont également des nombres).
```

2023-01-25 10:03 UTC, merged