ajout des exemples correspondant aux tutos déjà traduits
iOiurson/svelte-fr-docs pull request #39
Opened 2023-03-01 13:02 UTC by iOiurson

2023-03-04 08:57 UTC, Ennoriel requested changes

2023-03-04 08:57 UTC, Ennoriel commented on svelte/fr/examples/02-props/00-declaring-props/meta.json
> +	"title": "Declaring props"
```suggestion
	"title": "Déclarer des props"
```

2023-03-04 08:57 UTC, Ennoriel commented on svelte/fr/examples/02-props/01-default-values/meta.json
> +	"title": "Default values"
```suggestion
	"title": "Valeurs par défaut"
```

2023-03-04 08:57 UTC, Ennoriel commented on svelte/fr/examples/02-props/02-spread-props/meta.json
> +	"title": "Spread props"
```suggestion
	"title": "Décomposition des props"
```

2023-03-07 08:22 UTC, Ennoriel requested changes

2023-03-07 08:22 UTC, Ennoriel commented on svelte/fr/examples/03-logic/04-keyed-each-blocks/App.svelte
> +	Remove first thing
```suggestion
	Supprime le premier élément
```

2023-03-07 08:22 UTC, Ennoriel commented on svelte/fr/examples/03-logic/04-keyed-each-blocks/App.svelte
> +		<h2>Keyed</h2>
ce titre et le suivant ne sont pas traduits mais... comment le traduire ? Je mettrais peut être "Liste keyed" ?

2023-03-07 08:22 UTC, Ennoriel commented on svelte/fr/examples/03-logic/04-keyed-each-blocks/Thing.svelte
> +	<span style="background-color: {current}">current</span>
```suggestion
	<span style="background-color: {current}">courant</span>
```

2023-03-07 08:22 UTC, Ennoriel commented on svelte/fr/examples/03-logic/04-keyed-each-blocks/Thing.svelte
> +	<span style="background-color: {current}">current</span>
je ne sais pas s'il faut traduire

2023-03-07 08:22 UTC, Ennoriel commented on svelte/fr/tutorial/04-logic/05-keyed-each-blocks/app-b/App.svelte
> +		{ id: 5, color: 'gold' }
Je ne comprends pas la modification ?

2023-03-07 17:28 UTC, iOiurson commented on svelte/fr/examples/03-logic/04-keyed-each-blocks/Thing.svelte
> +	<span style="background-color: {current}">current</span>
oui, on a traduit dans le tuto, j'ai juste oublié de l'intégrer ici.

2023-03-07 17:29 UTC, iOiurson commented on svelte/fr/examples/03-logic/04-keyed-each-blocks/App.svelte
> +		<h2>Keyed</h2>
j'avais mis "Avec clé" dans le tuto

2023-03-07 17:29 UTC, iOiurson commented on svelte/fr/tutorial/04-logic/05-keyed-each-blocks/app-b/App.svelte
> +		{ id: 5, color: 'gold' }
Un copié-collé un peu violent

2023-03-07 17:34 UTC, merged