tutos/07
iOiurson/svelte-fr-docs pull request #41
Opened 2023-03-02 17:52 UTC by iOiurson

2023-03-02 19:54 UTC, MacFJA commented on svelte/fr/examples/06-lifecycle/00-onmount/App.svelte
> +		<p>loading...</p>
```suggestion
		<p>chargement...</p>
```

2023-03-02 19:54 UTC, MacFJA commented on svelte/fr/tutorial/07-lifecycle/01-onmount/app-a/App.svelte
> +		<p>loading...</p>
```suggestion
		<p>chargement...</p>
```

2023-03-02 19:54 UTC, MacFJA commented on svelte/fr/tutorial/07-lifecycle/01-onmount/app-b/App.svelte
> +		<p>loading...</p>
```suggestion
		<p>chargement...</p>
```

2023-03-02 19:54 UTC, MacFJA commented on svelte/fr/tutorial/07-lifecycle/02-ondestroy/app-a/Timer.svelte
> +	{interval} milliseconde{interval === 1 ? '' : 's'}
```suggestion
	{interval} milliseconde{interval > 1 ? 's' : ''}
```

2023-03-02 19:54 UTC, MacFJA commented on svelte/fr/examples/06-lifecycle/01-ondestroy/App.svelte
> +	{seconds} {seconds === 1 ? 'seconde' : 'secondes'}
```suggestion
	{seconds} {seconds > 1 ? 'secondes' : 'seconde'}
```

2023-03-02 19:54 UTC, MacFJA commented on svelte/fr/tutorial/07-lifecycle/02-ondestroy/app-a/App.svelte
> +		{seconds} {seconds === 1 ? 'seconde' : 'secondes'}
```suggestion
		{seconds} {seconds > 1 ? 'secondes' : 'seconde'}
```

2023-03-02 19:54 UTC, MacFJA commented on svelte/fr/tutorial/07-lifecycle/02-ondestroy/app-b/App.svelte
> +		{seconds} {seconds === 1 ? 'seconde' : 'secondes'}
```suggestion
		{seconds} {seconds > 1 ? 'secondes' : 'seconde'}
```

2023-03-02 19:54 UTC, MacFJA commented on svelte/fr/tutorial/07-lifecycle/02-ondestroy/app-b/Timer.svelte
> +	{interval} milliseconde{interval === 1 ? '' : 's'}
```suggestion
	{interval} milliseconde{interval > 1 ? 's' : ''}
```

2023-03-02 19:54 UTC, MacFJA commented on svelte/fr/tutorial/07-lifecycle/02-ondestroy/text.md
> +Par exemple, nous pouvons ajouter une fonction `setInterval` lorsque notre composant s'instancie, et nettoyer l'intervalle lorsqu'il n'est plus pertinent. Cela permet d'éviter des fuites de mémoire.
```suggestion
Par exemple, nous pouvons ajouter une fonction `setInterval` lorsque notre composant s'instancie, et supprimer l'intervalle lorsqu'il n'est plus pertinent. Cela permet d'éviter des fuites de mémoire.
```
?

2023-03-02 19:54 UTC, MacFJA commented on svelte/fr/tutorial/07-lifecycle/03-update/text.md
> +La fonction `beforeUpdate` prévoit une mise-à-jour à effectuer juste avant la mise-à-jour du <span class="vo">_DOM_</span>. `afterUpdate` est son alter-ego, utile pour exécuter du code une fois que l
> mise-à-jour à effectuer juste avant la mise-à-jour

Ça fait un peu redondant. Et peut prêter à confusion, non ?

2023-03-02 19:54 UTC, MacFJA commented on svelte/fr/tutorial/07-lifecycle/04-tick/text.md
> +La fonction `tick` est différente des autres fonctions de cycle de vie : vous pouvez l'appeler à n'importe quel moment, et non uniquement lorsque le composant est instancié. Cette fonction retourne u
```suggestion
La fonction `tick` est différente des autres fonctions de cycle de vie : vous pouvez l'appeler à n'importe quel moment, et pas uniquement lorsque le composant est instancié. Cette fonction retourne une promesse qui se résout dès que tous les changements d'état ont été appliqués au <span class="vo">_DOM_</span> (ou immédiatement, si aucun changement d'état n'est en attente).
```

2023-03-02 22:04 UTC, iOiurson commented on svelte/fr/tutorial/07-lifecycle/03-update/text.md
> +La fonction `beforeUpdate` prévoit une mise-à-jour à effectuer juste avant la mise-à-jour du <span class="vo">_DOM_</span>. `afterUpdate` est son alter-ego, utile pour exécuter du code une fois que l
En remaniant un peu :

```suggestion
La fonction `beforeUpdate` permet de prévoir une fonction à exécuter juste avant la mise-à-jour du <span class="vo">_DOM_</span>. `afterUpdate` est son alter-ego, utile pour exécuter du code une fois que le DOM est synchronisé avec votre donnée.
```

2023-03-04 09:13 UTC, Ennoriel requested changes

2023-03-04 09:13 UTC, Ennoriel commented on svelte/fr/examples/06-lifecycle/02-update/meta.json
> +	"title": "beforeUpdate and afterUpdate"
```suggestion
	"title": "beforeUpdate et afterUpdate"
```

2023-03-04 09:13 UTC, Ennoriel commented on svelte/fr/tutorial/07-lifecycle/01-onmount/text.md
> +Chaque instance de composant possède un **cycle de vie** qui débute lorsqu'elle est créée, et qui se termine lorsqu'elle est détruite. Il existe plusieurs fonctions qui vous permettent d'exécuter du
```suggestion
Chaque instance de composant possède un **cycle de vie** qui débute lorsqu'il est créé, et qui se termine lorsqu'il est détruit. Il existe plusieurs fonctions qui vous permettent d'exécuter du code à des moments clés de ce cycle de vie.
```
instance, composant et cycle sont tous les trois masculins 🤔

2023-03-04 09:13 UTC, Ennoriel commented on svelte/fr/tutorial/07-lifecycle/01-onmount/text.md
> +Si le <span class="vo">_callback_</span> de `onMount` retourne une fonction, celle-ci sera exécutée à la destruction de l'instance..
```suggestion
Si le <span class="vo">_callback_</span> de `onMount` retourne une fonction, celle-ci sera exécutée à la destruction de l'instance.
```

2023-03-04 09:13 UTC, Ennoriel commented on svelte/fr/tutorial/07-lifecycle/02-ondestroy/app-a/utils.js
> +		// Régler la fuite mémoire ici
```suggestion
		// Règle la fuite mémoire ici
```
je ne sais pas si ce changement est consistant avec les autres tutos mais à l'infinitif, ça fait bizarre je trouve

2023-03-04 09:13 UTC, Ennoriel commented on svelte/fr/tutorial/07-lifecycle/03-update/text.md
> +title: beforeUpdate and afterUpdate
```suggestion
title: beforeUpdate et afterUpdate
```

2023-03-06 07:08 UTC, iOiurson commented on svelte/fr/tutorial/07-lifecycle/01-onmount/text.md
> +Chaque instance de composant possède un **cycle de vie** qui débute lorsqu'elle est créée, et qui se termine lorsqu'elle est détruite. Il existe plusieurs fonctions qui vous permettent d'exécuter du
instance c'est féminin.

2023-03-06 07:10 UTC, iOiurson commented on svelte/fr/tutorial/07-lifecycle/02-ondestroy/app-a/utils.js
> +		// Régler la fuite mémoire ici
?

```suggestion
		// Réglez la fuite mémoire ici
```

2023-03-06 17:49 UTC, merged