Début de la traduction du chapitre 06
iOiurson/svelte-fr-docs pull request #5
Opened 2023-01-28 16:42 UTC by FlorentAzd

J'ai commencé la traduction du chapitre 6

2023-01-30 17:44 UTC, iOiurson requested changes

2023-01-30 17:44 UTC, iOiurson commented on svelte/fr/docs/06-accessibility-warnings.md
> +L'accessibilité (raccourcie à a11y) n'est pas toujours facile à obtenir correctement, cependant Svelte vous aidera en vous avertissant au moment de la compilation si vous écrivez un balisage inaccess
En général on essaie de garder certaines terminologies anglophones, lorsque c'est l'usage à l'oral.
Notamment:
- store
- markup

```suggestion
L'accessibilité (souvent raccourcie en "a11y") est un sujet complexe, qu'il est courant de mal implémenter. Pour vous aider, Svelte vous avertit au moment de la compilation si vous écrivez du markup non accessible. Toutefois, gardez à l'esprit que de nombreux problèmes d'accessibilité ne peuvent être identifiés qu'au moment de l'exécution, à l'aide d'autres outils automatisés et en testant manuellement votre application.
```

2023-01-30 17:44 UTC, iOiurson commented on svelte/fr/docs/06-accessibility-warnings.md
> +Voici une liste des contrôles d'accessibilité que Svelte fera pour vous.
```suggestion
Voici la liste des vérifications d'accessibilité que Svelte fera pour vous.
```

2023-01-30 17:44 UTC, iOiurson commented on svelte/fr/docs/06-accessibility-warnings.md
> +Appliquer aucun `accesskey` sur l'élément. Les touches d'accès sont des attributs HTML qui permettent aux développeurs Web d'attribuer des raccourcis clavier aux éléments. Les incohérences entre les
```suggestion
Veiller à ne pas utiliser l'attribut `accesskey` sur des éléments. L'attribut HTML `accesskey` permet aux développeurs web d'attribuer des raccourcis clavier aux éléments. Les incohérences entre les raccourcis clavier et les commandes clavier utilisées par le lecteur d'écran et les utilisateurs du clavier créent des complications d'accessibilité. Pour éviter les complications, les touches d'accès ne doivent pas être utilisées.
```

2023-01-30 17:44 UTC, iOiurson commented on svelte/fr/docs/06-accessibility-warnings.md
> +Certains éléments DOM réservés ne prennent pas en charge les rôles, états et propriétés ARIA. C'est souvent parce qu'ils ne sont pas visibles, par exemple `meta`, `html`, `script`, `style`. Cette règ
```suggestion
Certains éléments DOM spéciaux ne prennent pas en charge les rôles, états et propriétés ARIA. C'est souvent parce qu'ils ne sont pas visibles, comme `meta`, `html`, `script`, `style`. Cette règle garantit que ces éléments DOM ne contiennent pas des `aria-*` accessoires.
```

2023-01-30 17:44 UTC, iOiurson commented on svelte/fr/docs/06-accessibility-warnings.md
> +Veiller à ce que l’autofocus ne soit pas utilisé sur les éléments. Les éléments d'autofocus peuvent entraîner des problèmes de convivialité pour les utilisateurs voyants et non myopes.
```suggestion
Interdire l’usage d'`autofocus` sur les éléments. Le focus automatique d'éléments peut entraîner des problèmes d'usage pour les utilisateurs, qu'ils soient malvoyants, non voyants ou avec une vue parfaite.
```

2023-01-30 17:44 UTC, bleucitron commented on svelte/fr/docs/06-accessibility-warnings.md
> +<!-- A11y: Eviter d'utiliser autofocus -->
```suggestion
<!-- A11y: ne pas utiliser autofocus -->
```

2023-01-30 17:44 UTC, bleucitron commented on svelte/fr/docs/06-accessibility-warnings.md
> +<!-- A11y: Évitez d'utiliser la touches d'accès -->
```suggestion
<!-- A11y: ne pas utiliser accessKey -->
```

2023-01-30 17:44 UTC, iOiurson commented on svelte/fr/docs/06-accessibility-warnings.md
> +<!-- A11y: <meta> should not have aria-* attributes -->
```suggestion
<!-- A11y: <meta> ne devrait pas avoir d'attribut aria-* -->
```

2023-01-30 17:44 UTC, iOiurson commented on svelte/fr/docs/06-accessibility-warnings.md
> +Veiller à ce que `on:click` soit accompagné d'au moins l'un des éléments suivants: `onKeyUp`, `onKeyDown`, `onKeyPress`. Le codage du clavier est important pour les utilisateurs handicapés physiques
```suggestion
Veiller à ce que `on:click` soit accompagné d'au moins l'un des éléments suivants: `onKeyUp`, `onKeyDown`, `onKeyPress`. Penser à l'usage au clavier est important pour les utilisateurs avec des handicaps physiques qui ne peuvent pas utiliser de souris, pour les utilisateurs de liseuses d'écran, ainsi que pour la compatibilité AT.
```

2023-01-30 17:44 UTC, iOiurson commented on svelte/fr/docs/06-accessibility-warnings.md
> +Veiller à ce qu'aucun élément distrayant ne soit utilisé. Les éléments qui peuvent être distrayants visuellement peuvent causer des problèmes d'accessibilité avec les utilisateurs malvoyants. Ces élé
```suggestion
Veiller à ce qu'aucun élément distrayant ne soit utilisé. Les éléments distrayants visuellement peuvent causer des problèmes d'accessibilité avec les utilisateurs malvoyants. Ces éléments sont généralement dépréciés et doivent être évités.
```

2023-01-30 17:44 UTC, bleucitron commented on svelte/fr/docs/06-accessibility-warnings.md
> +<!-- A11y: Eviter les éléments <marquee> -->
```suggestion
<!-- A11y: éviter les éléments <marquee> -->
```

2023-01-30 17:44 UTC, bleucitron commented on svelte/fr/docs/06-accessibility-warnings.md
> +Certains éléments DOM sont utiles pour la navigation sur le lecteur d'écran et ne doivent pas être cachés.
```suggestion
Certains éléments DOM sont utiles pour la navigation avec lecteur d'écran et ne doivent pas être cachés.
```

2023-01-30 17:44 UTC, iOiurson commented on svelte/fr/docs/06-accessibility-warnings.md
> +Veiller à ce que l'attribut `alt` de la balise `img` ne contient pas le mot image ou photo. Les lecteurs d'écran annoncent déjà `img` éléments comme image. Il n'est pas nécessaire d'utiliser des mots
```suggestion
Veiller à ce que l'attribut `alt` des balises `img` ne contienne pas le mot "image" ou "photo". Les lecteurs d'écran décrivent déjà les éléments `img` comme étant des images. Il n'est pas nécessaire d'utiliser des mots tels que *photo* et / ou *image*.
```

2023-01-30 17:44 UTC, iOiurson commented on svelte/fr/docs/06-accessibility-warnings.md
> +<!-- aria-hidden, ne sera pas annoncer par le lecteur d'écran-->
```suggestion
<!-- aria-hidden, ne sera pas annoncé par le lecteur d'écran-->
```

2023-01-30 17:44 UTC, bleucitron commented on svelte/fr/docs/06-accessibility-warnings.md
> +Veiller à ce que le type de valeur utilisé soit correct pour les attributs `aria`. Par exemple, `aria-hidden` ne devrait recevoir qu'un booléen.
```suggestion
Veiller à ce que le bon type de valeur soit utilisé pour les attributs `aria`. Par exemple, `aria-hidden` ne devrait recevoir qu'un booléen.
```

2023-01-30 17:44 UTC, bleucitron commented on svelte/fr/docs/06-accessibility-warnings.md
> +<!-- A11y: La valeur de 'aria-hidden' doit être exactement `true` ou `false` -->
```suggestion
<!-- A11y: la valeur de 'aria-hidden' doit être exactement `true` ou `false` -->
```

2023-01-30 17:56 UTC, FlorentAzd commented on svelte/fr/docs/06-accessibility-warnings.md
> +<!-- A11y: La valeur de 'aria-hidden' doit être exactement `true` ou `false` -->
Bien noté pour les rectifications

2023-02-02 19:54 UTC, iOiurson approved these changes

2023-02-02 19:54 UTC, merged