Tutos/last
iOiurson/svelte-fr-docs pull request #62
Opened 2023-03-30 17:10 UTC by iOiurson

Je n'ai pas traduit les exemples `99-embeds` parce qu'ils ne sont plus sur le site officiel.

2023-03-30 20:17 UTC, patiboh commented on svelte/fr/examples/17-special-elements/04-svelte-window-bindings/App.svelte
> +		Faites défilez vers le bas
défiler

2023-03-30 20:28 UTC, patiboh commented on svelte/fr/tutorial/16-special-elements/03-svelte-element/app-a/App.svelte
> +	<p>Je suis une balise tag</p>
ne serait-ce pas une balise 'p' plutôt que tag ?

2023-03-30 20:31 UTC, patiboh commented on svelte/fr/tutorial/16-special-elements/04-svelte-window/text.md
> +> Comme pour les éléments du <span class="vo">_DOM_</span>, vous pouvez ajouter des [modificateurs d'évènements](/tutorial/event-modifiers) comme `preventDefault`.
c'est normal qu'il y ait un charactère '>' en debut de ligne ? (cela rendra un style quotation en Markdown)

2023-03-30 20:32 UTC, patiboh commented on svelte/fr/tutorial/16-special-elements/05-svelte-window-bindings/app-b/App.svelte
> +		Faites défilez vers le bas
défiler

2023-03-30 20:36 UTC, patiboh commented on svelte/fr/tutorial/16-special-elements/07-svelte-head/text.md
> +> En mode "rendu côté serveur" (<span class="vo">_SSR_</span>), le contenu de `<svelte:head>` est envoyé séparément du reste de votre <span class="vo">_HTML_</span>.
même commentaire qu'auparavant: le charactère '>' en debut de ligne, est-ce normal? (j'ai peut-être mal compris quelquechose ...)

2023-03-30 20:38 UTC, patiboh commented on svelte/fr/tutorial/16-special-elements/08-svelte-options/text.md
> +> Vous pouvez raccourcir avec `<svelte:options immutable/>` si vous préférez.
char '>'

2023-03-30 20:47 UTC, patiboh commented on svelte/fr/tutorial/17-module-context/02-module-exports/text.md
> +> Vous ne pouvez pas définir d'export par défaut, car le composant **est** l'export par défaut.
char '>' de citation en trop (sauf erreur de ma part)

2023-03-30 20:55 UTC, patiboh commented
Bravo!

2023-03-31 06:53 UTC, iOiurson commented on svelte/fr/examples/17-special-elements/04-svelte-window-bindings/App.svelte
> +		Faites défilez vers le bas
```suggestion
		Faites défiler vers le bas
```

2023-03-31 06:54 UTC, iOiurson commented on svelte/fr/tutorial/16-special-elements/03-svelte-element/app-a/App.svelte
> +	<p>Je suis une balise tag</p>
```suggestion
	<p>Je suis une balise p</p>
```

2023-03-31 06:55 UTC, iOiurson commented on svelte/fr/tutorial/16-special-elements/04-svelte-window/text.md
> +> Comme pour les éléments du <span class="vo">_DOM_</span>, vous pouvez ajouter des [modificateurs d'évènements](/tutorial/event-modifiers) comme `preventDefault`.
oui c'est comme ça à la base.

2023-03-31 06:55 UTC, iOiurson commented on svelte/fr/tutorial/16-special-elements/05-svelte-window-bindings/app-b/App.svelte
> +		Faites défilez vers le bas
```suggestion
		Faites défiler vers le bas
```

2023-03-31 06:57 UTC, iOiurson commented on svelte/fr/tutorial/16-special-elements/07-svelte-head/text.md
> +> En mode "rendu côté serveur" (<span class="vo">_SSR_</span>), le contenu de `<svelte:head>` est envoyé séparément du reste de votre <span class="vo">_HTML_</span>.
c'est comme ça que c'est écrit :
https://svelte.dev/tutorial/svelte-head

2023-03-31 06:57 UTC, iOiurson commented on svelte/fr/tutorial/16-special-elements/08-svelte-options/text.md
> +> Vous pouvez raccourcir avec `<svelte:options immutable/>` si vous préférez.
https://svelte.dev/tutorial/svelte-options

2023-03-31 06:57 UTC, iOiurson commented on svelte/fr/tutorial/17-module-context/02-module-exports/text.md
> +> Vous ne pouvez pas définir d'export par défaut, car le composant **est** l'export par défaut.
https://svelte.dev/tutorial/module-exports

2023-03-31 09:47 UTC, patiboh commented on svelte/fr/tutorial/16-special-elements/07-svelte-head/text.md
> +> En mode "rendu côté serveur" (<span class="vo">_SSR_</span>), le contenu de `<svelte:head>` est envoyé séparément du reste de votre <span class="vo">_HTML_</span>.
yes, autant pour moi!

2023-03-31 17:07 UTC, Ennoriel requested changes

2023-03-31 17:07 UTC, Ennoriel commented on svelte/fr/examples/17-special-elements/00-svelte-self/App.svelte
> +			name: "GIFs d'animaux",
```suggestion
			name: "GIF d'animaux",
```

2023-03-31 17:07 UTC, Ennoriel commented on svelte/fr/examples/20-7guis/04-7guis-timer/App.svelte
> +<button on:click="{() => elapsed = 0}">reset</button>
réinitialiser

2023-03-31 17:07 UTC, Ennoriel commented on svelte/fr/examples/21-miscellaneous/01-hacker-news/App.svelte
> +		// le routeur du pauvre !
j'ai pas compris la blague :p

2023-03-31 17:07 UTC, Ennoriel commented on svelte/fr/tutorial/16-special-elements/01-svelte-self/app-a/App.svelte
> +			name: "GIFs d'animaux",
```suggestion
			name: "GIF d'animaux",
```

2023-04-01 10:01 UTC, iOiurson commented on svelte/fr/examples/20-7guis/04-7guis-timer/App.svelte
> +<button on:click="{() => elapsed = 0}">reset</button>
```suggestion
<button on:click="{() => elapsed = 0}">réinitialiser</button>
```

2023-04-01 10:03 UTC, iOiurson commented on svelte/fr/examples/21-miscellaneous/01-hacker-news/App.svelte
> +		// le routeur du pauvre !
Ben c'est ça qui est littéralement écrit https://github.com/sveltejs/svelte/blob/master/site/content/examples/21-miscellaneous/01-hacker-news/App.svelte#L10

2023-04-01 10:04 UTC, iOiurson commented on svelte/fr/examples/17-special-elements/00-svelte-self/App.svelte
> +			name: "GIFs d'animaux",
Pkoi pas de "s" ? En VO ils en ont mis.

2023-04-01 11:38 UTC, Ennoriel commented on svelte/fr/examples/21-miscellaneous/01-hacker-news/App.svelte
> +		// le routeur du pauvre !
Autant pour moi, j'ai lu "le retour du pauvre"...

2023-04-01 11:39 UTC, Ennoriel commented on svelte/fr/examples/17-special-elements/00-svelte-self/App.svelte
> +			name: "GIFs d'animaux",
Les acronymes et abréviations ne prennent pas de "s" en français 🙄

2023-04-02 11:09 UTC, iOiurson commented on svelte/fr/examples/17-special-elements/00-svelte-self/App.svelte
> +			name: "GIFs d'animaux",
okok

2023-04-03 18:37 UTC, Ennoriel requested changes

2023-04-03 18:37 UTC, Ennoriel commented on svelte/fr/tutorial/16-special-elements/01-svelte-self/app-b/App.svelte
> +			name: "GIFs d'animaux",
```suggestion
			name: "GIF d'animaux",
```

2023-04-03 18:37 UTC, Ennoriel commented on svelte/fr/tutorial/16-special-elements/02-svelte-component/text.md
> +La valeur `this` peut être n'importe quel constructor de composant, ou une valeur <span class="vo">_falsy_</span> — si la valeur est <span class="vo">_falsy_</span>, aucun composant n'est rendu.
```suggestion
La valeur `this` peut être n'importe quel constructeur de composant, ou une valeur <span class="vo">_falsy_</span> — si la valeur est <span class="vo">_falsy_</span>, aucun composant n'est rendu.
```

2023-04-03 18:37 UTC, Ennoriel commented on svelte/fr/tutorial/16-special-elements/08-svelte-options/text.md
> +Ici nous prenons l'option `immutable` comme exemple. Dans cette application, les instances `<Todo>` clignotent lorsqu'elles recoivent une nouvelle donnée. Le clic sur un des éléments de la liste acti
```suggestion
Ici nous prenons l'option `immutable` comme exemple. Dans cette application, les instances `<Todo>` clignotent lorsqu'elles reçoivent une nouvelle donnée. Le clic sur un des éléments de la liste active ou désactive son état `done` en créant un nouveau tableau `todos` avec des données à jour. Cela entraîne le clignotement des **autres** `<Todo>`, même si au final aucun changement de <span class="vo">_DOM_</span> ne les concerne.
```

2023-04-03 18:37 UTC, Ennoriel commented on svelte/fr/tutorial/16-special-elements/08-svelte-options/text.md
> +* `immutable={false}` — par défaut. Svelt sera conservatif pour vérifier si les objets mutables ont changé ou non
```suggestion
* `immutable={false}` — par défaut. Svelte sera conservatif pour vérifier si les objets mutables ont changé ou non
```

2023-04-03 18:37 UTC, Ennoriel commented on svelte/fr/tutorial/17-module-context/01-sharing-code/app-a/AudioPlayer.svelte
> +		// À FAIRE: implémenter stopOther
```suggestion
		// À FAIRE: implémenter stopOthers
```

c'est peut-être une erreur en anglais mais j'irai pas faire la PR :p

2023-04-03 18:37 UTC, Ennoriel commented on svelte/fr/tutorial/17-module-context/02-module-exports/text.md
> +...et nous en servir dans un gestionnaire d'évènement :
```suggestion
...et nous en servir dans un gestionnaire d'évènements :
```

2023-04-03 18:37 UTC, Ennoriel commented on svelte/fr/tutorial/19-next-steps/01-congratulations/text.md
> +Vous avez terminé le tutoriel de Svelte et êtes maintenant prêt.e.s à construire des applications. Vous pouvez revenir aux différents chapitres à tout moment (cliquez sur le titre plus haut pour affi
On pets le Twitter fr ? SvelteSocietyFr ?

2023-04-03 19:42 UTC, iOiurson commented on svelte/fr/tutorial/19-next-steps/01-congratulations/text.md
> +Vous avez terminé le tutoriel de Svelte et êtes maintenant prêt.e.s à construire des applications. Vous pouvez revenir aux différents chapitres à tout moment (cliquez sur le titre plus haut pour affi
Hm, à cet endroit là, il mentionne le compte de Svelte, pas de SvelteSociety, donc je ne pense pas.

2023-04-03 19:44 UTC, Ennoriel commented on svelte/fr/tutorial/19-next-steps/01-congratulations/text.md
> +Vous avez terminé le tutoriel de Svelte et êtes maintenant prêt.e.s à construire des applications. Vous pouvez revenir aux différents chapitres à tout moment (cliquez sur le titre plus haut pour affi
ok

2023-04-03 19:44 UTC, merged