Updates
iOiurson/svelte-fr-docs pull request #67
Opened 2023-04-18 18:56 UTC by iOiurson

2023-05-09 18:03 UTC, Ennoriel requested changes

2023-05-09 18:03 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Note: Si vous souhaitez afficher un élément HTML de type `<slot>`, vous pouvez utiliser `<svelte:element this="slot" />`.
j'ai du lire les issues pour comprendre le besoin derrière ça (ce qui n'est vraiment pas évident dans la doc anglaise). C'est pourquoi j'ajouterai quelque chose du style "(utile pour les webcomponents notamment)"

2023-05-09 18:03 UTC, Ennoriel commented on svelte/fr/docs/06-accessibility-warnings.md
> +Elements with explicit or implicit roles defined contain only `aria-*` properties supported by that role.
```suggestion
```

2023-05-09 18:03 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +À l'instar de `<svelte:window>`, cet élément vous permet d'ajouter des gestionnaires d'évènement sur `document`, comme `visibilitychange`, qui ne sera pas déclenché sur `window`. Cet élément vous per
```suggestion
À l'instar de `<svelte:window>`, cet élément vous permet d'ajouter des gestionnaires d'évènement sur `document`, comme `visibilitychange`, qui n'est pas déclenché sur `window`. Cet élément vous permet aussi d'utiliser des [actions](/docs#template-syntax-element-directives-use-action) sur `document`.
```

2023-05-10 08:24 UTC, iOiurson commented on svelte/fr/docs/03-template-syntax.md
> +Note: Si vous souhaitez afficher un élément HTML de type `<slot>`, vous pouvez utiliser `<svelte:element this="slot" />`.
Ou juste mettre un lien vers la page MDN correspondantes aux `<slot>` HTML.

```suggestion
Note: Si vous souhaitez afficher [un élément HTML de type `<slot>`](https://developer.mozilla.org/fr/docs/Web/HTML/Element/slot), vous pouvez utiliser `<svelte:element this="slot" />`.
```

2023-05-10 16:45 UTC, merged