Translate component API
iOiurson/svelte-fr-docs pull request #8
Opened 2023-01-31 13:00 UTC by Ennoriel

2023-01-31 21:44 UTC, iOiurson requested changes
J'ai un doute sur comment afficher visuellement les anglicismes. Je me dis que ça pourrait bien de les différencier de *cette manière*, mais si on le fait il faudrait le faire systématiquement. Et on l'a pas fait jusque là.

Quel est ton avis ?

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Un composant rendu côté client est une classe Javascript correspondant à un composant compilé avec l'option `generate: 'dom'` (ou avec l'option `generate` non spécifié).
```suggestion
Un composant rendu côté client est une classe Javascript correspondant à un composant compilé avec l'option `generate: 'dom'` (ou avec l'option `generate` non spécifiée).
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +| `anchor` | `null` | Un enfant de la cible `target` à rendre immédiatement
```suggestion
| `anchor` | `null` | Un enfant de la cible `target` à rendre juste avant le composant
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Les enfants existants de la cible `target` sont ignorés.
Il y a peut-être quelque chose que je comprends mal.

Pour moi aussi les enfants sont ignorés, mais l'original dit qu'on les laisse en place... ce qui signifierait qu'ils ne sont pas ignorés ??
```suggestion
Les enfants existants de la cible `target` ne sont pas affectés.
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +L'option d'hydratation `hydrate` indique à Svelte de mettre à jour le DOM existant (habituellement à partir du rendu côté serveur) plutôt que de créer de nouveaux éléments. Cela ne fonctionnera que s
```suggestion
L'option d'hydratation `hydrate` indique à Svelte de mettre à jour le DOM existant (habituellement à partir du rendu côté serveur) plutôt que de créer de nouveaux éléments. Cela ne fonctionnera que si le composant a été compilé avec l'option [`hydratable: true`](/docs#compile-time-svelte-compile). L'hydratation de la section `<head>` ne fonctionnera que si le code rendu côté serveur a également été compilé avec l'option `hydratable: true`. Cette option a pour effet d'identifier chaque élément à l'intérieur de la section `<head>` de telle sorte que le composant sache quels éléments il peut supprimer pendant l'hydratation.
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Alors que les enfants de la cible `target` ne sont normalement pas modifiés, l'option `hydrate: true` causera leur suppression. Pour cette raison, l'option `anchor` ne peut pas être utilisée en même
Han, donc avec cette API de rendu client, et l'option `hydrate: false` (par défaut), les enfants de la `target` ne sont pas supprimés, donc ma suggestion plus haut est correcte.

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +L'appel de cette méthode déclenchera une mise à jour à la prochaine microtâche, le DOM **n'est pas** mise à jour de manière synchrone.
```suggestion
L'appel de cette méthode déclenchera une mise à jour à la prochaine micro-tâche — le DOM **n'est pas** mis à jour de manière synchrone.
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +`$on` enregistre un `callback` qui sera appelé à chaque émission d'un `event`.
C'est pas une suggestion forte, mais je préfère "génération". Tu peux ignorer si tu n'es pas d'accord.

```suggestion
`$on` enregistre un `callback` qui sera appelé à chaque génération d'un évènement de type `event`.
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +$on retourne une fonction dont l'exécution permet de supprimer l'écoute de cet événement.
```suggestion
`$on` retourne une fonction dont l'exécution permet de supprimer l'écoute de cet événement.
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Si un composant est compilé avec l'option `accessors: true`, chaque instance sera généré avec des getters et setters correspondant à chacune de ses propriétés. Mettre à jour une des propriétés déclen
Je me dis que c'est peut-être pas mal de mettre les mots anglophones qu'on ne veut pas traduire en italique, mais je sais pas si c'est une bonne idée, vu qu'on ne le fait pas pour store par exemple. Je veux bien ton avis.

```suggestion
Si un composant est compilé avec l'option `accessors: true`, chaque instance sera générée avec des *getters* et *setters* correspondant à chacune de ses propriétés. Mettre à jour une des propriétés déclenchera une mise à jour *synchrone*. Ce comportement est différent de la mise à jour asynchrone déclenchée par l'appel `component.$set(...)`.
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Par défaut, `accessors` est initialisé à `false`, à moins que vous ne compiliez un web component (voir section suivante).
```suggestion
Par défaut, `accessors` est initialisé à `false`, à moins que vous ne compiliez un *web component* (voir section suivante).
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +### API des web components
```suggestion
### API des *web components*
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Les composants Svelte peuvent également être compilés en web components (ou custom elements) en utilisant l'option `customElement: true`. Vous devez spécifier un nom de tag pour le composant en utili
```suggestion
Les composants Svelte peuvent également être compilés en *web components* (ou *custom elements*) en utilisant l'option `customElement: true`. Il est recommandé de spécifier un nom de tag pour le composant en utilisant la [balise](/docs#template-syntax-svelte-options) `<svelte:options>`.
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +	export let name = 'world';
```suggestion
	export let name = 'tout le monde';
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +<h1>Hello {name}!</h1>
```suggestion
<h1>Bonjour {name} !</h1>
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Une fois qu'un web component a été définit, il peut être utilisé comme un élément du DOM classique :
```suggestion
Une fois qu'un web component a été défini, il peut être utilisé comme un élément du DOM classique :
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Par défaut, les web components sont compilés avec l'option `accessors: true`, qui indique que n'importe quelle [`props`](/docs#template-syntax-attributes-and-props) sera exposée comme propriété de l'
```suggestion
Par défaut, les web components sont compilés avec l'option `accessors: true`, qui indique que n'importe quelle [`props`](/docs#template-syntax-attributes-and-props) sera exposée comme propriété de l'élément DOM (et sera traitée comme un attribut modifiable lorsque ça sera possible).
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Pour l'empécher, vous pouvez ajouter l'option `accessors={false}` à la balise `<svelte:options>`.
```suggestion
Pour empêcher ce comportement, vous pouvez ajouter l'option `accessors={false}` à la balise `<svelte:options>`.
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Les web components sont un bon moyen de packager des composants pour une utilisation dans une application développée dans une autre technologie que Svelte, puisqu'ils fonctionneront avec du HTML et J
"Javascript" ou "JavaScript" ?

Moi je préfère "Javascript", mais je crois que c'est "JavaScript" l'écriture "correcte".

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +* Le style est *encapsulé*, plutôt que simplement *scopé*. Cela signfie que tout style définit en dehors du composant (par exemple, celui définit dans un fichier `global.css` et celui définit avec `:
```suggestion
* Le style est *encapsulé*, plutôt que simplement *scopé*. Cela signifie que tout style défini en dehors du composant (par exemple, celui défini dans un fichier `global.css` et celui défini avec `:global(...)`) ne s'appliquera pas au web component
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +* Plutôt que d'être extrait dans un fichier .css séparé, le style est mis en propriété du composant
```suggestion
* Plutôt que d'être extrait dans un fichier `.css` séparé, le style est mis en propriété du composant
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +* Les web components ne sont généralement pas fait pour être rendus côté serveur, puisque le shadow DOM est invisible tant que Javascript n'est pas initialisé
```suggestion
* Les web components ne sont généralement pas faits pour être rendus côté serveur, puisque le *shadow DOM* est invisible tant que le code Javascript n'est pas chargé
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +* En Svelte, les éléments slottés sont rendus de manière *lazy*. Dans le DOM, le rendu est *eager*. En d'autres termes, le composant sera toujours créé même si l'élément `<slot>` est à l'intérieur d'
J'avoue, "eagerly" c'est chaud...

```suggestion
* En Svelte, les éléments slottés sont rendus de manière *lazy*. Dans le DOM, le rendu est "impatient". En d'autres termes, le composant sera toujours créé même si l'élément `<slot>` est à l'intérieur d'un bloc `{#if ...}`. De la même manière, inclure un `<slot>` dans un bloc `{#each ...}` ne rendra pas l'enfant plusieurs fois
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +* Des polyfills sont nécessaires pour supporter les plus vieux navigateurs
```suggestion
* Des *polyfills* sont nécessaires pour supporter de vieux navigateurs
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +A la différence des composants rendus côté client, les composants rendus côté serveurs n'ont pas de cycle de vie une fois qu'ils sont rendus, leur unique intérêt est de créer du HTML et du CSS. Pour
```suggestion
A la différence des composants rendus côté client, les composants rendus côté serveur n'ont pas de vie une fois qu'ils sont rendus, leur unique intérêt est de créer du HTML et du CSS. Pour cette raison, l'API est différente.
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Un composant rendu côté serveur expose une méthode `render` qui peut être appelé avec des propriétés optionnelles. La méthode retourne un object avec les propriétés  `head`, `html`, et `css`, où `hea
```suggestion
Un composant rendu côté serveur expose une méthode `render` qui peut être appelée avec des propriétés optionnelles. Cette méthode retourne un objet avec les propriétés  `head`, `html`, et `css`, où `head` contient les éléments de toutes les balises `<svelte:head>` présentes.
```

2023-01-31 21:44 UTC, bleucitron commented on svelte/fr/docs/04-run-time.md
> +Vous pouvez importer un composant directement à partir de Node.js en utilisant [`svelte/register`](/docs#run-time-svelte-register).
```suggestion
Vous pouvez importer un composant directement dans Node.js en utilisant [`svelte/register`](/docs#run-time-svelte-register).
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +La méthode `.render()` accepte les paramètres suivants :
J'ai pas fait attention à ce qu'on a utilisé jusque là, mais je suis plutôt "arguments" que "paramètres" de fonction. Je te laisse décider.

```suggestion
La méthode `.render()` accepte les arguments suivants :
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +| paramètre | valeur par défaut | description |
```suggestion
| argument | valeur par défaut | description |
```

2023-01-31 21:44 UTC, bleucitron commented on svelte/fr/docs/04-run-time.md
> +| `props` | `{}` | Un objet de propriété à passer au composant
```suggestion
| `props` | `{}` | Un objet de propriétés à passer au composant
```

2023-01-31 21:44 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +| paramètre | valeur par défaut | description |
```suggestion
| option | valeur par défaut | description |
```

2023-01-31 21:44 UTC, bleucitron commented on svelte/fr/docs/04-run-time.md
> +	// propriétés
```suggestion
	// props
```

2023-02-01 13:04 UTC, Ennoriel commented on svelte/fr/docs/04-run-time.md
> +A la différence des composants rendus côté client, les composants rendus côté serveurs n'ont pas de cycle de vie une fois qu'ils sont rendus, leur unique intérêt est de créer du HTML et du CSS. Pour
je préfère garder "cycle de vie" en entier 🙄

2023-02-01 13:04 UTC, Ennoriel commented on svelte/fr/docs/04-run-time.md
> +Les web components sont un bon moyen de packager des composants pour une utilisation dans une application développée dans une autre technologie que Svelte, puisqu'ils fonctionneront avec du HTML et J
Javascript, c'est un truc propriétaire Java il me semble alors il n'y a pas vraiment d'écriture "correcte". On devrait utiliser ECMAScript 😆. JavaScript semble utilisé par MDN alors partons pour ça

2023-02-02 12:47 UTC, iOiurson requested changes

2023-02-02 12:47 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Les composants Svelte peuvent également être compilés en *web components* (ou *custom elements*) en utilisant l'option `customElement: true`. Il est recommandé de spécifier un nom de tag pour le comp
```suggestion
Les composants Svelte peuvent également être compilés en *web components* (ou *custom elements*) en utilisant l'option `customElement: true`. Il est recommandé de spécifier un nom de tag pour le composant en utilisant la [balise `<svelte:options>`](/docs#template-syntax-svelte-options).
```

2023-02-02 12:47 UTC, iOiurson commented on svelte/fr/docs/04-run-time.md
> +Les web components sont un bon moyen de packager des composants pour une utilisation dans une application développée dans une autre technologie que Svelte, puisqu'ils fonctionneront avec du HTML et J
```suggestion
Les web components sont un bon moyen de packager des composants pour une utilisation dans une application développée dans une autre technologie que Svelte, puisqu'ils fonctionneront avec du HTML et JavaScript natifs mais aussi avec [la plupart des frameworks](https://custom-elements-everywhere.com/). Il y a cependant des différences importantes à connaître :
```

2023-02-02 13:27 UTC, merged