Template syntax suite
iOiurson/svelte-fr-docs pull request #9
Opened 2023-02-02 19:56 UTC by iOiurson

2023-02-02 21:13 UTC, MacFJA commented on svelte/fr/docs/03-template-syntax.md
> +Sur les éléments `<input>` de type `type=="file"`, vous pouvez utiliser `bind:files` pour obtenir la [`FileList` des fichiers sélectionnés](https://developer.mozilla.org/fr/docs/Web/API/FileList). Ce
```suggestion
Sur les éléments `<input>` de type `type="file"`, vous pouvez utiliser `bind:files` pour obtenir la [`FileList` des fichiers sélectionnés](https://developer.mozilla.org/fr/docs/Web/API/FileList). Cette liste est en lecture seule.
```

2023-02-02 21:13 UTC, MacFJA commented on svelte/fr/docs/03-template-syntax.md
> +	<option value="Guacamole (extra)">Guacamole (extra)</option>
```suggestion
	<option value="Guacamole (supplément)">Guacamole (supplément)</option>
```
?

2023-02-02 21:13 UTC, MacFJA commented on svelte/fr/docs/03-template-syntax.md
> +> Il est recommandé d'utiliser `css` plutôt que `tick`, si possible — les animations CSS sont exécutées sur un *thread* différent de celui de JS, évitant ainsi de ralentir les machines les moins puis
```suggestion
> Il est recommandé d'utiliser `css` plutôt que `tick`, si possible — les animations CSS sont exécutées sur un *fil d'exécution* différent de celui de JS, évitant ainsi de ralentir les machines les moins puissantes.
```
? 
[Wikipedia](https://fr.wikipedia.org/wiki/Thread_(informatique))

2023-02-02 21:13 UTC, MacFJA commented on svelte/fr/docs/03-template-syntax.md
> +```js
```suggestion
```ts
```
Pour avoir une meilleure coloration syntaxique

2023-02-02 21:13 UTC, MacFJA commented on svelte/fr/docs/03-template-syntax.md
> +Components can emit events using [createEventDispatcher](/docs#run-time-svelte-createeventdispatcher), or by forwarding DOM events. Listening for component events looks the same as listening for DOM
Traduction oubliée

2023-02-03 21:42 UTC, Ennoriel requested changes

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Utilisez la directive `on:` pour écouter des évènements DOM.
```suggestion
Utilisez la directive `on:` pour écouter des évènements du DOM.
```

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Utilisez la directive `on:` pour écouter des évènements DOM.
C'est à plusieurs endroits, j'hésite

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +* `passive` — améliore la perfomance du défilement pour les évènement touch/wheel (Svelte l'ajoutera automatiquement lorsque cela n'est pas problématique)
```suggestion
* `passive` — améliore la perfomance du défilement pour les évènement touch/wheel (Svelte l'ajoutera automatiquement lorsque qu'il détecte que ce n'est pas problématique)
```

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Si la directive `on:` est utilisée sans valeur, le composant *relaiera* l'évènement, ce qui permet à un parent du composant d'écouter cet évènement.
```suggestion
Si la directive `on:` est utilisée sans valeur, l'évènement sera transmis à son composant parent, ce qui permet lui permettra de l'écouter.
```

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +En général, la donnée *descend* du parent vers l'enfant. La directive `bind:` permet à la donnée de remonter de l'enfant vers le parent. Le plus souvent ces liaisons sont spécifiques à des éléments p
```suggestion
La directive `bind:` permet à la donnée de remonter d'un enfant vers son parent. Le plus souvent ces liaisons sont spécifiques à des éléments particuliers.
```
Je supprimerais presque la première phrase qui rend le tout plus confus. Et je ne comprends pas la dernière phrase x)

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +En général, la donnée *descend* du parent vers l'enfant. La directive `bind:` permet à la donnée de remonter de l'enfant vers le parent. Le plus souvent ces liaisons sont spécifiques à des éléments p
J'ai relu la version anglais, sinon : 
```suggestion
Les données sont généralement transmises d'un élément parent à un élément enfant. La directive `bind:` permet aux données de remonter d'un enfant vers son parent. Le plus souvent ces liaisons sont spécifiques à des éléments particuliers.
```
Je ne comprends toujours pas la fin, même en anglais x)

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +L'exemple le plus simple d'une liaison reflète la valeur d'une propriété, comme `input.value`.
```suggestion
L'exemple le plus simple d'un *bindng* reflète la valeur d'une propriété, comme `input.value`.
```
J'aime pas trop reflète mais j'ai pas mieux à l'instant. J'irais peut-être plus sur un truc plus long et qui s'éloigne de la VO : L'exemple le plus simple d'un *bindng* permet de ... la valeur d'une propriété


Franchement cette partie est naze en anglais. Ca aurait été bien de faire apparaitre "pour un élément HTML, le binding permet d'associer la valeur d'un attribut à une variable. Dès que la valeur est mise à jour par une action utilisateur ou algorithmique, la variable sera mise à jour".......

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Les valeurs numériques sont traitées comme des nombres ; même si `input.value` est une chaîne de caractères pour le DOM, Svelte traitera cette valeur comme un nombre. Si l'input est vide ou invalide
```suggestion
Les valeurs numériques sont traitées comme des nombres ; même si `input.value` est une chaîne de caractères pour le DOM, Svelte traitera cette valeur comme un nombre. Si l'input est vide ou invalide (dans le cas de `type="number"` par exemple), la valeur sera `undefined`.
```

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Sur les éléments `<input>` de type `type="file"`, vous pouvez utiliser `bind:files` pour obtenir la [`FileList` des fichiers sélectionnés](https://developer.mozilla.org/fr/docs/Web/API/FileList). Cet
```suggestion
Sur les éléments `<input>` de type fichier (`type="file"`), vous pouvez utiliser `bind:files` pour obtenir la [liste des fichiers téléchargés `FileList`](https://developer.mozilla.org/fr/docs/Web/API/FileList). Cette liste est en lecture seule.
```

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Si vous utilisez des directives `bind:` conjointement à des directives `on:`, l'ordre dans lequel elles sont définies affectera la valeur de la variable liée lorsque la fonction d'écoute sera appelée
```suggestion
Si vous utilisez des directives `bind:` et `on:` en même temps, l'ordre dans lequel elles sont définies affectera la valeur de la variable liée lorsque la fonction d'écoute sera appelée.
```

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Une liaison sur un `<select>` correspond à la propriété `value` sur l'`<option>` sélectionnée, qui peut être n'importe quelle valeur (pas uniquement des chaînes de caractères, comme c'est le cas en g
```suggestion
Une liaison sur un `<select>` correspond à la propriété `value` de l'`<option>` sélectionnée, qui peut être n'importe quelle valeur (pas uniquement des chaînes de caractères, comme c'est le cas en général dans le DOM).
```

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Les vidéos ont de plus des liaisons en lecture seule pour les attributs `videoWidth` et `videoHeight`.
```suggestion
Les vidéos ont également des liaisons en lecture seule pour les attributs `videoWidth` et `videoHeight`.
```

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +##### Liaisons de bloc
```suggestion
##### Liaisons des éléments de type `block`
```

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +##### Liaisons de bloc
Si tu le traduis, il faut peut être un s à bloc

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +<!-- les inputs radio groupés sont mutuellement exclusifs -->
```suggestion
<!-- les inputs de type radio groupés sont mutuellement exclusifs -->
```
ou alors les radio boutons

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +<!-- les inputs checkbox groupés remplissent un tableau -->
```suggestion
<!-- les inputs de type checkbox groupés remplissent un tableau -->
```
ou alors les checkbox tout court

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Une directive de `class:` fournit une méthode rapide pour ajouter ou enlever une classe à un élément.
```suggestion
Une directive `class:` fournit une méthode rapide pour ajouter ou enlever une classe à un élément.
```

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +<!-- Syntaxe raccourcie, quand les noms correspondent -->
```suggestion
<!-- Syntaxe raccourcie, quand le nom de la variable correspond au nom de la classe -->
```

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +<!-- Syntaxe raccourcie, quand les noms correspondent -->
```suggestion
<!-- Syntaxe raccourcie, quand le nom de la variable correspond au nom de la propriété -->
```

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Une action peut avoir un argument. Si la valeur renvoyée a une méthode `update`, celle-ci sera exécutée à chaque fois que cet argument changera, juste après que Svelte a appliqué les modifications au
```suggestion
Une action peut avoir un argument. Si la valeur renvoyée possède une méthode `update`, celle-ci sera exécutée à chaque fois que cet argument changera, juste après que Svelte a appliqué les modifications au *markup*.
```

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Quand un bloc transitionne vers sa sortie, tous les éléments au sein du bloc, y compris ceux n'ayant pas de transition propre, sont laissés dans le DOM tant que toutes les transitions du bloc se soie
```suggestion
Quand un bloc transitionne vers sa sortie, tous les éléments au sein du bloc, y compris ceux n'ayant pas de transition propre, sont laissés dans le DOM tant que toutes les transitions du bloc ne soient terminées.
```

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +La fonction est régulièrement appelée *avant* que la transition ne commence, avec différentes valeurs pour `t` et `u`.
L'anglais n'est pas très explicite et du coup le français non plus. Moi qui me suis amusé avec les transitions, je comprends mais ce n'est vraiment pas accessible à un nouveau je trouve

2023-02-03 21:42 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +		Le renard marron et véloce saute au-dessus du chien fainéant
C'est un pangramme (https://fr.wikipedia.org/wiki/The_quick_brown_fox_jumps_over_the_lazy_dog) ! en vrai je ne savais pas que ça s’appelait comme ça. Du coup, on en mets un en français ? :p

2023-02-04 12:45 UTC, iOiurson commented on svelte/fr/docs/03-template-syntax.md
> +Si la directive `on:` est utilisée sans valeur, le composant *relaiera* l'évènement, ce qui permet à un parent du composant d'écouter cet évènement.
J'aime bien l'idée de "relais":

"relaiera l'évènement à son parent, ce qui permettra à ce dernier de l'écouter."

?

2023-02-04 12:49 UTC, iOiurson commented on svelte/fr/docs/03-template-syntax.md
> +En général, la donnée *descend* du parent vers l'enfant. La directive `bind:` permet à la donnée de remonter de l'enfant vers le parent. Le plus souvent ces liaisons sont spécifiques à des éléments p
Je trouve que c'est important de mentionner explicitement la notion de *descendant*, parce que c'est un concept fondateur de React, dont Svelte s'est tout de même inspiré.

```suggestion
Les données sont généralement transmises en flux *descendant*, c'est-à-dire d'un élément parent à un élément enfant. La directive `bind:` permet aux données de remonter d'un enfant vers son parent. Le plus souvent ces liaisons sont spécifiques à des éléments particuliers, comme les `<input>`.
```

La dernière phrase évoque (il me semble) qu'en général `bind:` est utilisé sur des éléments HTML particuliers, type `input`. On peut le mentionner pour expliciter.

2023-02-04 12:56 UTC, bleucitron commented on svelte/fr/docs/03-template-syntax.md
> +L'exemple le plus simple d'une liaison reflète la valeur d'une propriété, comme `input.value`.
Est-ce qu'on décide d'utiliser *binding* partout, quitte à mettre (liaison) au moins la première fois ?

Voici ma suggestion plus longue, qui s'écarte de la doc officielle:

```suggestion
L'exemple le plus simple d'un *binding* permet de lier la valeur d'un attribut (la `value` d'un `<input>` par exemple) à une variable. Lorsqu'un tel binding existe, si la variable liée est mise à jour, alors la valeur de l'attribut change également ; de même si la valeur de l'attribut est mise à jour par l'élément, la variable change pour prendre cette valeur. On parle alors de flux de données **bidirectionnel**.
```

2023-02-04 12:59 UTC, iOiurson commented on svelte/fr/docs/03-template-syntax.md
> +Sur les éléments `<input>` de type `type="file"`, vous pouvez utiliser `bind:files` pour obtenir la [`FileList` des fichiers sélectionnés](https://developer.mozilla.org/fr/docs/Web/API/FileList). Cet
Je garderais sélectionnés je pense.

```suggestion
Sur les éléments `<input>` de type fichier (`type="file"`), vous pouvez utiliser `bind:files` pour obtenir la [liste des fichiers sélectionnés `FileList`](https://developer.mozilla.org/fr/docs/Web/API/FileList). Cette liste est en lecture seule.
```

2023-02-04 13:00 UTC, iOiurson commented on svelte/fr/docs/03-template-syntax.md
> +Si vous utilisez des directives `bind:` conjointement à des directives `on:`, l'ordre dans lequel elles sont définies affectera la valeur de la variable liée lorsque la fonction d'écoute sera appelée
```suggestion
Si vous utilisez des directives `bind:` et `on:` sur le même élément, l'ordre dans lequel elles sont définies affectera la valeur de la variable liée lorsque la fonction d'écoute sera appelée.
```

2023-02-04 13:02 UTC, iOiurson commented on svelte/fr/docs/03-template-syntax.md
> +Les vidéos ont de plus des liaisons en lecture seule pour les attributs `videoWidth` et `videoHeight`.
```suggestion
Les vidéos ont des liaisons en lecture seule supplémentaires pour les attributs `videoWidth` et `videoHeight`.
```

2023-02-04 13:07 UTC, iOiurson commented on svelte/fr/docs/03-template-syntax.md
> +<!-- les inputs radio groupés sont mutuellement exclusifs -->
J'aime pas trop utiliser "bouton" pour un radio ou un checkbox, parce que c'est pas du tout un bouton.

Et "input de type radio" je trouve ça un peu lourd.

Mais si c'est vraiment bloquant pour toi, on peut éventuellement écrire :

```suggestion
<!-- les boutons radio groupés sont mutuellement exclusifs -->
```

2023-02-04 13:09 UTC, iOiurson commented on svelte/fr/docs/03-template-syntax.md
> +<!-- les inputs checkbox groupés remplissent un tableau -->
```suggestion
<!-- les checkbox groupées remplissent un tableau -->
```

**Une** checkbox non ?

2023-02-04 13:12 UTC, iOiurson commented on svelte/fr/docs/03-template-syntax.md
> +Quand un bloc transitionne vers sa sortie, tous les éléments au sein du bloc, y compris ceux n'ayant pas de transition propre, sont laissés dans le DOM tant que toutes les transitions du bloc se soie
```suggestion
Quand un bloc transitionne vers sa sortie, tous les éléments au sein du bloc, y compris ceux n'ayant pas de transition propre, sont laissés dans le DOM tant que toutes les transitions du bloc ne sont pas terminées.
```

2023-02-04 13:14 UTC, iOiurson commented on svelte/fr/docs/03-template-syntax.md
> +La fonction est régulièrement appelée *avant* que la transition ne commence, avec différentes valeurs pour `t` et `u`.
Il me semble que c'est plus clair dans les tutos.

La section Docs est plus destinée à un public un peu averti.

2023-02-04 13:16 UTC, iOiurson commented on svelte/fr/docs/03-template-syntax.md
> +		Le renard marron et véloce saute au-dessus du chien fainéant
Ah je savais pas...

Du coup:

```suggestion
		Portez ce vieux whisky au juge blond qui fume
```

2023-02-06 16:52 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Si la directive `on:` est utilisée sans valeur, le composant *relaiera* l'évènement, ce qui permet à un parent du composant d'écouter cet évènement.
oui, c'est bien :)

2023-02-06 16:57 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +En général, la donnée *descend* du parent vers l'enfant. La directive `bind:` permet à la donnée de remonter de l'enfant vers le parent. Le plus souvent ces liaisons sont spécifiques à des éléments p
oui, c'est bien :)

2023-02-06 16:58 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +L'exemple le plus simple d'une liaison reflète la valeur d'une propriété, comme `input.value`.
je préfère binding oui

2023-02-06 16:59 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Sur les éléments `<input>` de type `type="file"`, vous pouvez utiliser `bind:files` pour obtenir la [`FileList` des fichiers sélectionnés](https://developer.mozilla.org/fr/docs/Web/API/FileList). Cet
ok

2023-02-06 16:59 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Si vous utilisez des directives `bind:` conjointement à des directives `on:`, l'ordre dans lequel elles sont définies affectera la valeur de la variable liée lorsque la fonction d'écoute sera appelée
yes

2023-02-06 16:59 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Les vidéos ont de plus des liaisons en lecture seule pour les attributs `videoWidth` et `videoHeight`.
ok

2023-02-06 17:01 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +<!-- les inputs radio groupés sont mutuellement exclusifs -->
radio boutons ? ahah
on peut laisser input radio si tu veux aussi. C'est pas critique et tout le monde comprend les 3 options (même radio bouton)

2023-02-06 17:01 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +<!-- les inputs checkbox groupés remplissent un tableau -->
oui une

2023-02-06 17:02 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Quand un bloc transitionne vers sa sortie, tous les éléments au sein du bloc, y compris ceux n'ayant pas de transition propre, sont laissés dans le DOM tant que toutes les transitions du bloc se soie
ok

2023-02-06 17:43 UTC, Ennoriel requested changes

2023-02-06 17:43 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Contrairement à `transition:`, les transitions appliquées avec `in:` et `out:` ne sont pas bi-directionnelles — une transition entrante (*in*) continuera sa course en parallèle de la transition sorta
```suggestion
Contrairement à `transition:`, les transitions appliquées avec `in:` et `out:` ne sont pas bi-directionnelles. Si le bloc est supprimé pendant la transition en cours, la transition entrante (*in*) continuera sa course en parallèle de la transition sortante (*out*), plutôt que d'être inversée. Si une transition sortante est annulée, les transitions seront rejouées du début.
```

2023-02-06 17:43 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Les animations peuvent être définies par des fonctions fournissant un `node`, un objet `animation`, et n'importe quels `parameters` en arguments. L'argument `animation` est un objet ayant les proprié
```suggestion
Les animations peuvent être définies par des fonctions fournissant un `node`, un objet `animation`, et n'importe quels `parameters` en arguments. L'argument `animation` est un objet ayant les propriétés `from` et `to`, chacune contenant un [DOMRect](https://developer.mozilla.org/fr/docs/Web/API/DOMRect#Properties) décrivant la géométrie de l'élément dans ses positions de départ (`start`) et arrivée (`end`). La propriété `from` est le DOMRect de l'élément dans sa position de départ, la propriété `to` est le DOMRect de l'élément dans sa position d'arrivée après que la liste ait été réordonnée et le DOM mis à jour.
```

2023-02-06 17:43 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +L'argument `t` passé à `css` est une valeur qui va de `0` à `1` avec que la fonction `easing` a été appliquée. L'argument `u` est égal à `1 - t`.
```suggestion
L'argument `t` passé à la méthode `css` est une valeur qui va de `0` à `1` après que la fonction `easing` ait été appliquée. L'argument `u` est égal à `1 - t`.
```

2023-02-06 17:43 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +<UnComposant on:peuimporte={handler} />
```suggestion
<UnComposant on:peuImporte={handler} />
```

2023-02-06 17:43 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +<UnComposant on:peuimporte />
```suggestion
<UnComposant on:peuImporte />
```

2023-02-06 17:43 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +**Note**: Faites attention, cette syntaxe ajoute une `<div>` à votre markup, qui pourra être ciblée accidentellement par votre CSS. Ayez conscience de cet ajout d'élément lorsque vous utilisez cette
```suggestion
**Note**: Faites attention, cette syntaxe ajoute une `<div>` à votre *markup*, qui pourra être ciblée accidentellement par votre CSS. Ayez conscience de cet ajout d'élément lorsque vous utilisez cette fonctionnalité.
```

2023-02-06 17:43 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Les composants permettent aussi `bind:this`, permettant d'interagir avec les instances de composant programmatiquement.
```suggestion
Les composants permettent aussi d'utiliser la directive `bind:this`, permettant d'interagir avec les instances de composant programmatiquement.
```

2023-02-06 17:43 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Le contenu est exposé dans le composant enfant avec l'élément `<slot>`, qui peut avoir un contenu par défaut qui sera utilisé si aucun enfant n'est fourni.
```suggestion
Le contenu est exposé dans le composant enfant avec l'élément `<slot>`. Il est possible de définir un contenu par défaut qui sera utilisé si aucun enfant n'est fourni.
```

2023-02-06 17:43 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Le contenu est exposé dans le composant enfant avec l'élément `<slot>`, qui peut avoir un contenu par défaut qui sera utilisé si aucun enfant n'est fourni.
pour éviter la phrase longue avec le "qui ... qui ..."

2023-02-06 17:43 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +L'objet `$$slots` a comme clés les noms des slots passés au composant par le parent. Si le parent ne fournit pas un slot avec un nom particulier, ce nom ne sera pas présent dans `$$slots`. Cela perme
Je trouve la tournure "Si le parent ne fournit pas un slot avec un nom particulier, ce nom ne sera pas présent dans `$$slots`." compliqué mais je n'ai pas mieux

2023-02-06 17:43 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Les slors peuvent être rendus zéro ou plusieurs fois, et peuvent passer des valeurs *en retour* au parent en utilisant des props. Le parent expose ces valeurs au *template* de slot avec la directive
```suggestion
Les slots peuvent être rendus zéro ou plusieurs fois, et peuvent passer des valeurs *en retour* au parent en utilisant des props. Le parent expose ces valeurs au *template* de slot avec la directive `let:`.
```

2023-02-06 18:47 UTC, iOiurson commented on svelte/fr/docs/03-template-syntax.md
> +Les composants permettent aussi `bind:this`, permettant d'interagir avec les instances de composant programmatiquement.
Deux fois "permet" dans la même phrase...

```suggestion
Les composants peuvent aussi recevoir la directive `bind:this`, permettant d'interagir avec les instances de composant programmatiquement.
```

2023-02-06 18:50 UTC, iOiurson commented on svelte/fr/docs/03-template-syntax.md
> +L'objet `$$slots` a comme clés les noms des slots passés au composant par le parent. Si le parent ne fournit pas un slot avec un nom particulier, ce nom ne sera pas présent dans `$$slots`. Cela perme
Alternative ?

```suggestion
Si le parent ne fournit pas un slot avec un nom particulier, l'objet`$$slots` n'aura pas de propriété avec le même nom.
```

2023-02-06 18:53 UTC, iOiurson commented on svelte/fr/docs/03-template-syntax.md
> +Si la directive `on:` est utilisée sans valeur, le composant *relaiera* l'évènement, ce qui permet à un parent du composant d'écouter cet évènement.
J'ai commit la mauvaise suggestion, je laisse ce commentaire ouvert pour me rappeler de le changer plus tard.

2023-02-08 17:58 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +Les composants permettent aussi `bind:this`, permettant d'interagir avec les instances de composant programmatiquement.
je l'avais relevé aussi mais avec l'autre tournure ça choquait moins

2023-02-08 17:59 UTC, Ennoriel commented on svelte/fr/docs/03-template-syntax.md
> +L'objet `$$slots` a comme clés les noms des slots passés au composant par le parent. Si le parent ne fournit pas un slot avec un nom particulier, ce nom ne sera pas présent dans `$$slots`. Cela perme
oui, c'est bien

2023-02-09 19:21 UTC, merged